/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lectura_escritura_archivos;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import  javax.swing.JTable;
/**
 *
 * @author Estudiante
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    File archivo;
    public Main() {
       initComponents();
    }
    void mostrarerror(String titulo, String mensaje){
    JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.ERROR_MESSAGE);
    
    }
    void limpiartabla(JTable DateTable){
    DefaultTableModel model = (DefaultTableModel) DateTable.getModel();
    model.setRowCount(0);
    }
    void guardaraArchivo(){
        try (BufferedWriter bw= new BufferedWriter (new FileWriter(archivo))) {
            int Filas =DateTable.getRowCount();
            
            DefaultTableModel model = (DefaultTableModel) DateTable.getModel();
            for (int i = 0; i < Filas; i++) {
               Object codigo = model.getValueAt(i, 0);
               Object nombre = model.getValueAt(i, 1);
               Object promedio = model.getValueAt(i, 2);
               bw.write(codigo+","+nombre+","+promedio);
               bw.newLine();
            }
        } catch (IOException ex) {
            mostrarerror("Error Con Archivo","No se puede escribir en el archivo");
        } catch(NullPointerException ex){
        mostrarerror("Datos Faltantes","Los datos en la tabla no estan completos");
        limpiartabla(DateTable);
       }catch(NumberFormatException ex){
        mostrarerror("Error en datos","Verifique los datos ingresados");
       
       }catch(Exception ex){
        mostrarerror("Error","Error inesperado");
        ex.printStackTrace();
       }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        agregarFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        tfc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfp = new javax.swing.JTextField();
        btnaddn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DateTable = new javax.swing.JTable();
        btnadd = new javax.swing.JButton();
        btng = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();

        agregarFrame.setMinimumSize(new java.awt.Dimension(429, 300));

        jLabel2.setText("Codigo");

        tfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        tfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnActionPerformed(evt);
            }
        });

        jLabel4.setText("Promedio");

        tfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpActionPerformed(evt);
            }
        });

        btnaddn.setText("Agregar ");
        btnaddn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarFrameLayout = new javax.swing.GroupLayout(agregarFrame.getContentPane());
        agregarFrame.getContentPane().setLayout(agregarFrameLayout);
        agregarFrameLayout.setHorizontalGroup(
            agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarFrameLayout.createSequentialGroup()
                .addGroup(agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarFrameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(agregarFrameLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarFrameLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, agregarFrameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(agregarFrameLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnaddn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarFrameLayout.setVerticalGroup(
            agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addComponent(btnaddn)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(395, 339));

        jLabel1.setText("Archivo");

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DateTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                DateTableCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DateTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DateTable);
        if (DateTable.getColumnModel().getColumnCount() > 0) {
            DateTable.getColumnModel().getColumn(0).setResizable(false);
            DateTable.getColumnModel().getColumn(1).setResizable(false);
            DateTable.getColumnModel().getColumn(2).setResizable(false);
        }

        btnadd.setText("Agregar");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btng.setText("Guardar");
        btng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngActionPerformed(evt);
            }
        });

        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnadd)
                        .addGap(18, 18, 18)
                        .addComponent(btng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bteliminar)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btng)
                    .addComponent(bteliminar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // agregar filtro a filechooser
        FileNameExtensionFilter filter =
            new FileNameExtensionFilter ("Archivos .txt","txt","texto");
    fc.setFileFilter(filter);
    fc.showOpenDialog(this);
    int opcion = fc.showOpenDialog(this);
        if (opcion ==JFileChooser.APPROVE_OPTION) {
             archivo = fc.getSelectedFile();
             tf.setText(archivo.getAbsolutePath());
             
             
             //tomar el modelo de la tabla
             DefaultTableModel model = (DefaultTableModel) DateTable.getModel();
             
             
             
             try (Scanner lector = new Scanner(archivo)){
                //mientras archivo tenga otra linea
                while(lector.hasNextLine()){
                    //pedir la linea
                String linea = lector.nextLine();
                //separar los datos
                String[] datos = linea.split(",");
                long codigo = Long.parseLong(datos[0]);
                String nombre = datos[1];
                double promedio = Double.parseDouble(datos[2]);
                //agegar datos ala tabla
                model.addRow(new Object[]{codigo,nombre,promedio});
                }
            } catch (FileNotFoundException ex) {
                mostrarerror("error en el archivo","error al leer el arcivo");
            }catch (NumberFormatException ex) {
               
            }catch (Exception ex) {
                //todo eviar mensaje al usuario
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       tfc.setText("");
       tfn.setText("");
       tfp.setText("");
       
       agregarFrame.setVisible(true);
       
    }//GEN-LAST:event_btnaddActionPerformed

    private void btngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngActionPerformed
 guardaraArchivo();   
    }//GEN-LAST:event_btngActionPerformed

    private void tfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcActionPerformed

    private void tfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnActionPerformed

    private void tfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpActionPerformed

    private void btnaddnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnActionPerformed
DefaultTableModel model = (DefaultTableModel) DateTable.getModel();
String codigo = tfc.getText();
String nombre = tfn.getText();
double promedio = Double.parseDouble(tfp.getText()); 
model.addRow(new Object[]{codigo,nombre,promedio});
 agregarFrame.setVisible(false);
    }//GEN-LAST:event_btnaddnActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
      //hallar fila
      int fila = DateTable.getSelectedRow();
      //tomar modelo tabla
      DefaultTableModel model = (DefaultTableModel) DateTable.getModel();
      //eliminar fila
      model.removeRow(fila);
      guardaraArchivo();
    }//GEN-LAST:event_bteliminarActionPerformed

    private void DateTableCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DateTableCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTableCaretPositionChanged

    private void DateTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DateTableInputMethodTextChanged
    guardaraArchivo();
    }//GEN-LAST:event_DateTableInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DateTable;
    private javax.swing.JFrame agregarFrame;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddn;
    private javax.swing.JButton btng;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField tfc;
    private javax.swing.JTextField tfn;
    private javax.swing.JTextField tfp;
    // End of variables declaration//GEN-END:variables
}
